# Generated by Django 4.0.4 on 2022-04-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(verbose_name='Min value')),
                ('max_value', models.IntegerField(verbose_name='Max value')),
                ('avarage_value', models.FloatField(verbose_name='Avarage value')),
            ],
            options={
                'verbose_name': 'Heart rate',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('password', models.CharField(max_length=30, unique=True, verbose_name='Password')),
                ('country', models.CharField(max_length=3, null=True, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('serial_number', models.CharField(max_length=30, unique=True, verbose_name='Serial number')),
            ],
            options={
                'verbose_name': 'Person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.TimeField(verbose_name='Length of sleep')),
                ('wake_up_time', models.TimeField(verbose_name='Wake up time')),
                ('number_of_wake_ups', models.IntegerField(verbose_name='Number of wake ups')),
                ('deep_sleep', models.FloatField(verbose_name='Deep sleep')),
            ],
            options={
                'verbose_name': 'Sleep',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(verbose_name='Min value')),
                ('max_value', models.FloatField(verbose_name='Max value')),
                ('avarage_value', models.FloatField(verbose_name='Avarage value')),
            ],
            options={
                'verbose_name': 'Temperature',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heart_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistiky.heart_rate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistiky.person')),
                ('sleep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistiky.sleep')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistiky.temperature')),
            ],
            options={
                'verbose_name': 'Statistic',
                'ordering': ['date'],
            },
        ),
    ]
